Fixed bug in code Example
If the response passing through the ResponseExtractor has 0 as a key, it breaks with 
    
    TypeError: Cannot set property '0' of undefined

defining the originalElement member before populating it avoids this bug.